<?php

namespace KD\CoreBundle\Repository;

use KD\CoreBundle\Entity\User;
/**
 * QCMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *  Retourne la liste des QCMs
     *  Charge les notes pour affichage
     */
    public function allWithNotes(){
        
        $query = $this->_em->createQuery("SELECT q, n "
                . "FROM KDCoreBundle:QCM q "
                . "LEFT JOIN q.notes n "
                . "ORDER BY q.deadline ASC");

        return $query->getResult();
    }
    
    /**
     *  Retourne un QCM par son id
     *  Charge les entités nécessaires à l'affichage de son résultat
     */
    public function oneByIdWithEntities($id_qcm){
        
        $query = $this->_em->createQuery("SELECT qcm, question, reponse, note, eleve "
                . "FROM KDCoreBundle:QCM qcm "
                . "JOIN qcm.questions question "
                . "JOIN question.reponses reponse "
                . "LEFT JOIN qcm.notes note "
                . "LEFT JOIN note.eleve eleve "
                . "WHERE qcm.id = ?1");
        
        $query->setParameter(1,$id_qcm);

        return $query->getOneOrNullResult();
    }
    
   /**
    * Retourne la liste des qcms ayant été rendu par un $eleve
    * 
    * @param User $eleve
    * @return type
    */
   public function findSubmittedBy(User $eleve){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT q FROM KDCoreBundle:QCM q JOIN q.notes n WHERE n.eleve = ?1'
            )
            ->setParameter(1, $eleve)
            ->getResult();
    }
    
}
